debug: false
spring:
  datasource:
    druid:
      username: root
      url: jdbc:mysql://localhost:3306/activiti?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
  #activiti:
  #  check-process-definitions: false
  #  job-executor-activate: true
dubbo:
  #<dubbo:provider accesslog="true" timeout="2000" retries="0" />
  provider:
    accesslog: true
    timeout: 2000
    retries: 0
    server: true
  #<dubbo:registry protocol="zookeeper" address="127.0.0.1:2181" client="curator" register="true" group="test"/>
  registry:
    address: zookeeper://127.0.0.1:2181
    register: true
    group: test
    client: curator
    #<dubbo:protocol name="dubbo" port="20880" serialization="java" accesslog="true" />
  protocol:
    name: dubbo
    port: 20880
    serialization: java
    accesslog: true
    #<dubbo:application name="demo-provider"/>
  application:
    name: demo-provider
    qos-enable: true
    qos-port: 22222
  scan:
    base-packages: com.asiainfo.service.impl

# Dubbo Health
## StatusChecker Name defaults (default : "memory", "load" )
## StatusChecker Name extras (default : empty )
management:
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true
mybatis:
  type-aliases-package: com.asiainfo.entity
logging:
  level:
    com.asiainfo.mapper: DEBUG
